### ISSUE TITLE
Synchronization primitives needed for C code

### ISSUE THREAD

**Issue by bogdanm** [ARMmbed/core-util#74]
Our `CriticalSectionLock` is fine, but can only be used from C++ code. It turns out that we also need synchronization primitives for C code (see for example https://github.com/ARMmbed/sal-driver-lwip-k64f-eth/issues/3), so these need to be written.

**Comment by bremoran** [comment]
https://github.com/ARMmbed/core-util/pull/18

**Comment by hugovincent** [comment]
Hopefully goes without saying, but can you please do this such that there is only one piece of code for the primitives rather than duplicating the same functionality in both C and C++ (e.g. if you need to re-write it in C, then can you modify the C++ version to wrap the C version). Critical sections are very, well, _critical_, and having two implementations of them that might behave subtly differently is an unacceptable risk.

**Comment by bogdanm** [comment]
Fixed by a number of different commits for various platforms.
